### ISSUE TITLE
yuki_builder.py  whisper 命令执行失败

### ISSUE THREAD

**Issue by mabuyun** [LC1332/Chat-Haruhi-Suzumiya#23]
按照[文档](https://github.com/LC1332/Chat-Haruhi-Suzumiya/tree/main/yuki_builder#%E4%BB%8E%E8%A7%86%E9%A2%91%E4%B8%AD%E6%8F%90%E5%8F%96%E5%AD%97%E5%B9%95) 从视频中提取字幕时，以下命令报错

```
python yuki_builder.py whisper -input_video <input_video> -srt_folder <srt_folder>

Traceback (most recent call last):
  File "yuki_builder.py", line 7, in <module>
    from video_preprocessing.video_process import run_bgm_remover
  File "/data/repo/chat-haruhi-suzumiya/yuki_builder/video_preprocessing/video_process.py", line 1, in <module>
    from .uvr5 import uvr_prediction, uvr5_names
  File "/data/repo/chat-haruhi-suzumiya/yuki_builder/video_preprocessing/uvr5/__init__.py", line 1, in <module>
    from .process import (
  File "/data/repo/chat-haruhi-suzumiya/yuki_builder/video_preprocessing/uvr5/process.py", line 26, in <module>
    for name in os.listdir(weight_uvr5_root):
FileNotFoundError: [Errno 2] No such file or directory: '/data/repo/chat-haruhi-suzumiya/yuki_builder/video_preprocessing/uvr5/uvr5_weights'
```

**Comment by LC1332** [comment]
@ariafyy 帮他看看

**Comment by mabuyun** [comment]
里面的 [readme](https://github.com/LC1332/Chat-Haruhi-Suzumiya/blob/main/yuki_builder/video_preprocessing/uvr5/README.md) 给出了下载链接
